title: <p align="center"> Sharada MG</p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sharada-mg-she-her-hers-41744675/">LinkedIn</a> |
  <a href="https://github.com/Sharada-MG/Portfolio.git">GitHub</a>
  
  <br>   
  Delivery Manager | Strategic Thinking With High Outstanding People Connect | Customer Centric | Initiative & Proposals | 
  Agile Delivery | CSM | SAFe Leading Agilist | PRINCE2 |
    
  
  <br>
  </p>


theme: jekyll-theme-minimal
